name: parcel_delivery_app
description: "A new Flutter project."
publish_to: 'none'

version: 3.0.11+4

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_svg: ^2.0.16
  image_picker: ^1.1.2
  flutter_rating_bar: ^4.0.1
  intl: 0.20.2
  intl_phone_field: ^3.2.0
  keyboard_actions: ^4.2.0
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.2
  country_picker: ^2.0.27
  syncfusion_flutter_datepicker: ^31.1.19
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  http_parser: ^4.1.2
  http: ^1.3.0
  geolocator: ^14.0.2
  location: ^8.0.0
  google_maps_flutter: ^2.12.1
  mime: ^2.0.0
  flutter_image_compress: ^2.4.0
  geocoding: ^4.0.0
  firebase_messaging:
  firebase_core:
  firebase_auth:
  google_sign_in: ^7.2.0
  device_info_plus: ^12.2.0
  cached_network_image: ^3.4.1
  loading_animation_widget: ^1.3.0
  custom_rating_bar: ^3.0.0
  flutter_widget_from_html: ^0.17.0
  permission_handler: ^12.0.1
  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/dev_images/
    - assets/languages/
  fonts:
    - family: AeonikTRIAL
      fonts:
        - asset: assets/fonts/AeonikTRIAL-Regular.otf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf